/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import Image from 'next/image'
import Link from 'next/link'
import { Container, CssBaseline, Grid, Typography, Button } from '@mui/material';
import Head from 'next/head';
import React from 'react';
import Header from '../components/Layout/Header';
import { background, container, text } from './about';
import FourOhFour from '../public/images/2456051.jpg'
import HomeIcon from '@mui/icons-material/Home';
import {icon} from './index'

const Custom404: React.FC = () => {

  return (
    <>
      <Head>
        <title>404 | Robert Inez</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CssBaseline />
      <main css={background}>
        <Container css={container}>
        <Grid
            container
            justifyContent='center'
            alignItems='center'
            spacing={6}
            direction='row'
          >
            <Grid item md={6} sx={{textAlign: 'center'}}>
            <Typography variant='h2' align='center' css={text} gutterBottom>
                {/* eslint-disable-next-line react/no-unescaped-entities */}
                The page you were looking for could not be found!
            </Typography>
                <Link href='/' passHref>
                    <Button variant='contained' size='large' color='secondary'>
                      <HomeIcon css={icon} />
                      Go Home
                    </Button>
                </Link>
            </Grid>
            <Grid item md={6}>
            <Image src={FourOhFour} alt='404 error image' loading='lazy' layout='responsive'  />
            <Typography variant='subtitle2' css={text} gutterBottom>
                <a href="https://www.freepik.com/vectors/business">Business vector created by pikisuperstar - www.freepik.com</a>
              </Typography>
            </Grid>
          </Grid>
        </Container>
      </main>
    </>
  );
};

export default Custom404;
