/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx, CSSObject } from '@emotion/react';
import React from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import { CssBaseline, Grid, Container } from '@mui/material';
import Header from '../components/Layout/Header';
import Timeline from '../components/Timeline/Timeline';
import { background, container } from './about';

const Experience: NextPage = () => {
  return (
    <>
      <Head>
        <title>Experience | Robert Inez</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CssBaseline />
          <Header header='Experience' />
      <main css={background}>
        <Container css={container} maxWidth='xl'>
          <Grid
            container
            justifyContent='center'
            alignItems='center'
            spacing={6}
            direction='row'
          >
            <Grid item md={12}>
              <Timeline />
            </Grid>
          </Grid>
        </Container>
      </main>
    </>
  );
};

export default Experience;
