/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx, css, CSSObject } from '@emotion/react';
import React from 'react';
import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {
  Box,
  Container,
  Grid,
  Button,
  CssBaseline,
  Typography,
} from '@mui/material';
import { Work } from '@mui/icons-material';
import Typewriter from 'typewriter-effect';

const title: CSSObject = {
  margin: '0',
  lineHeight: '1.15',
  fontSize: '4rem',
  opacity: 1,
  color: 'hsl(60, 30%, 96%)',
};

const main: CSSObject = {
  padding: '5rem, 0',
  flex: 1,
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
};

const description: CSSObject = {
  lineHeight: '1.5',
  fontSize: '1.5rem',
  color: '#f8f8f2',
};

export const icon: CSSObject = {
  marginRight: '1rem',
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home | Robert Inez</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CssBaseline />
      <main className={styles.container}>
        <Container css={main}>
          <Grid
            container
            justifyContent='center'
            alignItems='center'
            spacing={6}
            direction='row'
          >
            <Grid item md={12}>
              <Typography variant='h1' align='center' css={title} gutterBottom>
                Robert Inez
              </Typography>
              <Typography
                css={description}
                variant='h4'
                align='center'
                gutterBottom
              >
                Fullstack Web Developer skilled in:
                <Typewriter
                  options={{
                    strings: [
                      'React',
                      'Javascript',
                      'Typescript',
                      'MySQL',
                      'NodeJS',
                      'ExpressJS',
                      'CSS',
                    ],
                    autoStart: true,
                    loop: true,
                  }}
                />
              </Typography>
              <Typography>
                <Box display='flex' justifyContent='center' alignItems='center'>
                  <Link href='/projects' passHref>
                    <Button variant='contained' size='large' color='secondary'>
                      <Work css={icon} />
                      See my work
                    </Button>
                  </Link>
                </Box>
              </Typography>
            </Grid>
          </Grid>
        </Container>
      </main>
    </>
  );
};

export default Home;
